//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionInfo) DeepCopyInto(out *EncryptionInfo) {
	*out = *in
	if in.EncryptionType != nil {
		in, out := &in.EncryptionType, &out.EncryptionType
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionInfo.
func (in *EncryptionInfo) DeepCopy() *EncryptionInfo {
	if in == nil {
		return nil
	}
	out := new(EncryptionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceInfo) DeepCopyInto(out *PerformanceInfo) {
	*out = *in
	if in.IopsLimit != nil {
		in, out := &in.IopsLimit, &out.IopsLimit
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceInfo.
func (in *PerformanceInfo) DeepCopy() *PerformanceInfo {
	if in == nil {
		return nil
	}
	out := new(PerformanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfo) DeepCopyInto(out *StoragePolicyInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfo.
func (in *StoragePolicyInfo) DeepCopy() *StoragePolicyInfo {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoList) DeepCopyInto(out *StoragePolicyInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoragePolicyInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoList.
func (in *StoragePolicyInfoList) DeepCopy() *StoragePolicyInfoList {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePolicyInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoSpec) DeepCopyInto(out *StoragePolicyInfoSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoSpec.
func (in *StoragePolicyInfoSpec) DeepCopy() *StoragePolicyInfoSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoStatus) DeepCopyInto(out *StoragePolicyInfoStatus) {
	*out = *in
	if in.StorageTypeInfo != nil {
		in, out := &in.StorageTypeInfo, &out.StorageTypeInfo
		*out = new([]StorageTypeInfo)
		if **in != nil {
			in, out := *in, *out
			*out = make([]StorageTypeInfo, len(*in))
			copy(*out, *in)
		}
	}
	if in.VolumeTypeInfo != nil {
		in, out := &in.VolumeTypeInfo, &out.VolumeTypeInfo
		*out = new(VolumeTypeInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyInfo != nil {
		in, out := &in.TopologyInfo, &out.TopologyInfo
		*out = new(TopologyInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionInfo != nil {
		in, out := &in.EncryptionInfo, &out.EncryptionInfo
		*out = new(EncryptionInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PerformanceInfo != nil {
		in, out := &in.PerformanceInfo, &out.PerformanceInfo
		*out = new(PerformanceInfo)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoStatus.
func (in *StoragePolicyInfoStatus) DeepCopy() *StoragePolicyInfoStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageTypeInfo) DeepCopyInto(out *StorageTypeInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageTypeInfo.
func (in *StorageTypeInfo) DeepCopy() *StorageTypeInfo {
	if in == nil {
		return nil
	}
	out := new(StorageTypeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfo) DeepCopyInto(out *TopologyInfo) {
	*out = *in
	if in.AccessibleZones != nil {
		in, out := &in.AccessibleZones, &out.AccessibleZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfo.
func (in *TopologyInfo) DeepCopy() *TopologyInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTypeInfo) DeepCopyInto(out *VolumeTypeInfo) {
	*out = *in
	if in.SupportedBlockVolumeModes != nil {
		in, out := &in.SupportedBlockVolumeModes, &out.SupportedBlockVolumeModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedFileVolumeModes != nil {
		in, out := &in.SupportedFileVolumeModes, &out.SupportedFileVolumeModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTypeInfo.
func (in *VolumeTypeInfo) DeepCopy() *VolumeTypeInfo {
	if in == nil {
		return nil
	}
	out := new(VolumeTypeInfo)
	in.DeepCopyInto(out)
	return out
}
