//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStoragePolicyInfoReference) DeepCopyInto(out *ClusterStoragePolicyInfoReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStoragePolicyInfoReference.
func (in *ClusterStoragePolicyInfoReference) DeepCopy() *ClusterStoragePolicyInfoReference {
	if in == nil {
		return nil
	}
	out := new(ClusterStoragePolicyInfoReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfo) DeepCopyInto(out *StoragePolicyInfo) {
	*out = *in
	out.Spec = in.Spec
	out.TypeMeta = in.TypeMeta
	in.Status.DeepCopyInto(&out.Status)
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfo.
func (in *StoragePolicyInfo) DeepCopy() *StoragePolicyInfo {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePolicyInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoList) DeepCopyInto(out *StoragePolicyInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoragePolicyInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoList.
func (in *StoragePolicyInfoList) DeepCopy() *StoragePolicyInfoList {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePolicyInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoSpec) DeepCopyInto(out *StoragePolicyInfoSpec) {
	*out = *in
	out.ClusterStoragePolicyInfoRef = in.ClusterStoragePolicyInfoRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoSpec.
func (in *StoragePolicyInfoSpec) DeepCopy() *StoragePolicyInfoSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePolicyInfoStatus) DeepCopyInto(out *StoragePolicyInfoStatus) {
	*out = *in
	if in.TopologyInfo != nil {
		in, out := &in.TopologyInfo, &out.TopologyInfo
		*out = new(Topology)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeCapabilities != nil {
		in, out := &in.VolumeCapabilities, &out.VolumeCapabilities
		*out = make(map[VolumeCapability]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ZonalVolumeCapabilities != nil {
		in, out := &in.ZonalVolumeCapabilities, &out.ZonalVolumeCapabilities
		*out = make(map[ZonalVolumeCapability]ZoneList, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(ZoneList, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePolicyInfoStatus.
func (in *StoragePolicyInfoStatus) DeepCopy() *StoragePolicyInfoStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePolicyInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topology) DeepCopyInto(out *Topology) {
	*out = *in
	if in.AccessibleZones != nil {
		in, out := &in.AccessibleZones, &out.AccessibleZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topology.
func (in *Topology) DeepCopy() *Topology {
	if in == nil {
		return nil
	}
	out := new(Topology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ZoneList) DeepCopyInto(out *ZoneList) {
	{
		in := &in
		*out = make(ZoneList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneList.
func (in ZoneList) DeepCopy() ZoneList {
	if in == nil {
		return nil
	}
	out := new(ZoneList)
	in.DeepCopyInto(out)
	return *out
}
