# See https://cloud.google.com/cloud-build/docs/build-config
# See https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/global/gcb-docker-gcloud
timeout: 2700s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240718-5ef92b5c36
    entrypoint: make
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
      - DOCKER_BUILDKIT=1
      - GOTOOLCHAIN=auto
    args:
      - deploy
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'