// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsFileAccessConfig) DeepCopyInto(out *CnsFileAccessConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsFileAccessConfig.
func (in *CnsFileAccessConfig) DeepCopy() *CnsFileAccessConfig {
	if in == nil {
		return nil
	}
	out := new(CnsFileAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnsFileAccessConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsFileAccessConfigList) DeepCopyInto(out *CnsFileAccessConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CnsFileAccessConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsFileAccessConfigList.
func (in *CnsFileAccessConfigList) DeepCopy() *CnsFileAccessConfigList {
	if in == nil {
		return nil
	}
	out := new(CnsFileAccessConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnsFileAccessConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsFileAccessConfigSpec) DeepCopyInto(out *CnsFileAccessConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsFileAccessConfigSpec.
func (in *CnsFileAccessConfigSpec) DeepCopy() *CnsFileAccessConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CnsFileAccessConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsFileAccessConfigStatus) DeepCopyInto(out *CnsFileAccessConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsFileAccessConfigStatus.
func (in *CnsFileAccessConfigStatus) DeepCopy() *CnsFileAccessConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CnsFileAccessConfigStatus)
	in.DeepCopyInto(out)
	return out
}
