/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties from the source into the target.
func (in *CnsNodeVmBatchAttachment) DeepCopyInto(out *CnsNodeVmBatchAttachment) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new CnsNodeVmBatchAttachment.
func (in *CnsNodeVmBatchAttachment) DeepCopy() *CnsNodeVmBatchAttachment {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object from the CnsNodeVmBatchAttachment.
func (in *CnsNodeVmBatchAttachment) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the source into the target.
func (in *CnsNodeVmBatchAttachmentList) DeepCopyInto(out *CnsNodeVmBatchAttachmentList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CnsNodeVmBatchAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentList.
func (in *CnsNodeVmBatchAttachmentList) DeepCopy() *CnsNodeVmBatchAttachmentList {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object from the CnsNodeVmBatchAttachmentList.
func (in *CnsNodeVmBatchAttachmentList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the source into the target.
func (in *CnsNodeVmBatchAttachmentSpec) DeepCopyInto(out *CnsNodeVmBatchAttachmentSpec) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentSpec.
func (in *CnsNodeVmBatchAttachmentSpec) DeepCopy() *CnsNodeVmBatchAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the source into the target.
func (in *CnsNodeVmBatchAttachmentStatus) DeepCopyInto(out *CnsNodeVmBatchAttachmentStatus) {
	*out = *in
	if in.VolumeStatus != nil {
		in, out := &in.VolumeStatus, &out.VolumeStatus
		*out = make(map[string]VolumeStatus, len(*in))
		for key, val := range *in {
			var outVal VolumeStatus
			val.DeepCopyInto(&outVal)
			(*out)[key] = outVal
		}
	}
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentStatus.
func (in *CnsNodeVmBatchAttachmentStatus) DeepCopy() *CnsNodeVmBatchAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the source into the target.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
}

// DeepCopy creates a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the source into the target.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
}

// DeepCopy creates a new VolumeStatus.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}
