// build : ignore_autogenerated

/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
	if in.Error != "" {
		out.Error = in.Error
	}
	if in.CnsVolumeID != "" {
		out.CnsVolumeID = in.CnsVolumeID
	}
	if in.Diskuuid != "" {
		out.Diskuuid = in.Diskuuid
	}
	return
}

// DeepCopy creates a new VolumeStatus that is a deep copy of the original.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *CnsNodeVmBatchAttachmentSpec) DeepCopyInto(out *CnsNodeVmBatchAttachmentSpec) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentSpec that is a deep copy of the original.
func (in *CnsNodeVmBatchAttachmentSpec) DeepCopy() *CnsNodeVmBatchAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	return
}

// DeepCopy creates a new VolumeSpec that is a deep copy of the original.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *CnsNodeVmBatchAttachmentStatus) DeepCopyInto(out *CnsNodeVmBatchAttachmentStatus) {
	*out = *in
	if in.VolumeStatus != nil {
		in, out := &in.VolumeStatus, &out.VolumeStatus
		*out = make(map[string]VolumeStatus, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentStatus that is a deep copy of the original.
func (in *CnsNodeVmBatchAttachmentStatus) DeepCopy() *CnsNodeVmBatchAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *CnsNodeVmBatchAttachment) DeepCopyInto(out *CnsNodeVmBatchAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy creates a new CnsNodeVmBatchAttachment that is a deep copy of the original.
func (in *CnsNodeVmBatchAttachment) DeepCopy() *CnsNodeVmBatchAttachment {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties from the receiver into the passed-in argument, which must be non-nil.
func (in *CnsNodeVmBatchAttachmentList) DeepCopyInto(out *CnsNodeVmBatchAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CnsNodeVmBatchAttachment, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy creates a new CnsNodeVmBatchAttachmentList that is a deep copy of the original.
func (in *CnsNodeVmBatchAttachmentList) DeepCopy() *CnsNodeVmBatchAttachmentList {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnsNodeVmBatchAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an implementation of runtime.Object.
func (in *CnsNodeVmBatchAttachment) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(CnsNodeVmBatchAttachment)
	in.DeepCopyInto(out)
	return out
}