// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsvSphereVolumeMigration) DeepCopyInto(out *CnsvSphereVolumeMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsvSphereVolumeMigration.
func (in *CnsvSphereVolumeMigration) DeepCopy() *CnsvSphereVolumeMigration {
	if in == nil {
		return nil
	}
	out := new(CnsvSphereVolumeMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnsvSphereVolumeMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsvSphereVolumeMigrationList) DeepCopyInto(out *CnsvSphereVolumeMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CnsvSphereVolumeMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsvSphereVolumeMigrationList.
func (in *CnsvSphereVolumeMigrationList) DeepCopy() *CnsvSphereVolumeMigrationList {
	if in == nil {
		return nil
	}
	out := new(CnsvSphereVolumeMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnsvSphereVolumeMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsvSphereVolumeMigrationSpec) DeepCopyInto(out *CnsvSphereVolumeMigrationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsvSphereVolumeMigrationSpec.
func (in *CnsvSphereVolumeMigrationSpec) DeepCopy() *CnsvSphereVolumeMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(CnsvSphereVolumeMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnsvSphereVolumeMigrationStatus) DeepCopyInto(out *CnsvSphereVolumeMigrationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnsvSphereVolumeMigrationStatus.
func (in *CnsvSphereVolumeMigrationStatus) DeepCopy() *CnsvSphereVolumeMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(CnsvSphereVolumeMigrationStatus)
	in.DeepCopyInto(out)
	return out
}
