apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-raw-block-restore
spec:
  storageClassName: example-raw-block-sc
  dataSource:
    name: example-raw-block-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi