/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/cnsvolumemetadata/v1alpha1"
)

// FakeCnsVolumeMetadatas implements CnsVolumeMetadataInterface
type FakeCnsVolumeMetadatas struct {
	Fake *FakeCnsV1alpha1
	ns   string
}

var cnsvolumemetadatasResource = schema.GroupVersionResource{Group: "cns.vmware.com", Version: "v1alpha1", Resource: "cnsvolumemetadatas"}

var cnsvolumemetadatasKind = schema.GroupVersionKind{Group: "cns.vmware.com", Version: "v1alpha1", Kind: "CnsVolumeMetadata"}

// Get takes name of the cnsVolumeMetadata, and returns the corresponding cnsVolumeMetadata object, and an error if there is any.
func (c *FakeCnsVolumeMetadatas) Get(name string, options v1.GetOptions) (result *v1alpha1.CnsVolumeMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cnsvolumemetadatasResource, c.ns, name), &v1alpha1.CnsVolumeMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CnsVolumeMetadata), err
}

// List takes label and field selectors, and returns the list of CnsVolumeMetadatas that match those selectors.
func (c *FakeCnsVolumeMetadatas) List(opts v1.ListOptions) (result *v1alpha1.CnsVolumeMetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cnsvolumemetadatasResource, cnsvolumemetadatasKind, c.ns, opts), &v1alpha1.CnsVolumeMetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CnsVolumeMetadataList{ListMeta: obj.(*v1alpha1.CnsVolumeMetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.CnsVolumeMetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cnsVolumeMetadatas.
func (c *FakeCnsVolumeMetadatas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cnsvolumemetadatasResource, c.ns, opts))

}

// Create takes the representation of a cnsVolumeMetadata and creates it.  Returns the server's representation of the cnsVolumeMetadata, and an error, if there is any.
func (c *FakeCnsVolumeMetadatas) Create(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (result *v1alpha1.CnsVolumeMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cnsvolumemetadatasResource, c.ns, cnsVolumeMetadata), &v1alpha1.CnsVolumeMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CnsVolumeMetadata), err
}

// Update takes the representation of a cnsVolumeMetadata and updates it. Returns the server's representation of the cnsVolumeMetadata, and an error, if there is any.
func (c *FakeCnsVolumeMetadatas) Update(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (result *v1alpha1.CnsVolumeMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cnsvolumemetadatasResource, c.ns, cnsVolumeMetadata), &v1alpha1.CnsVolumeMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CnsVolumeMetadata), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCnsVolumeMetadatas) UpdateStatus(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (*v1alpha1.CnsVolumeMetadata, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cnsvolumemetadatasResource, "status", c.ns, cnsVolumeMetadata), &v1alpha1.CnsVolumeMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CnsVolumeMetadata), err
}

// Delete takes name of the cnsVolumeMetadata and deletes it. Returns an error if one occurs.
func (c *FakeCnsVolumeMetadatas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cnsvolumemetadatasResource, c.ns, name), &v1alpha1.CnsVolumeMetadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCnsVolumeMetadatas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cnsvolumemetadatasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CnsVolumeMetadataList{})
	return err
}

// Patch applies the patch and returns the patched cnsVolumeMetadata.
func (c *FakeCnsVolumeMetadatas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CnsVolumeMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cnsvolumemetadatasResource, c.ns, name, pt, data, subresources...), &v1alpha1.CnsVolumeMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CnsVolumeMetadata), err
}
