/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	cnsv1alpha1 "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/cnsvolumemetadata/v1alpha1"
	versioned "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/client/informers/externalversions/internalinterfaces"
	v1alpha1 "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/client/listers/cns/v1alpha1"
)

// CnsVolumeMetadataInformer provides access to a shared informer and lister for
// CnsVolumeMetadatas.
type CnsVolumeMetadataInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CnsVolumeMetadataLister
}

type cnsVolumeMetadataInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCnsVolumeMetadataInformer constructs a new informer for CnsVolumeMetadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCnsVolumeMetadataInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCnsVolumeMetadataInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCnsVolumeMetadataInformer constructs a new informer for CnsVolumeMetadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCnsVolumeMetadataInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CnsV1alpha1().CnsVolumeMetadatas(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CnsV1alpha1().CnsVolumeMetadatas(namespace).Watch(options)
			},
		},
		&cnsv1alpha1.CnsVolumeMetadata{},
		resyncPeriod,
		indexers,
	)
}

func (f *cnsVolumeMetadataInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCnsVolumeMetadataInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cnsVolumeMetadataInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cnsv1alpha1.CnsVolumeMetadata{}, f.defaultInformer)
}

func (f *cnsVolumeMetadataInformer) Lister() v1alpha1.CnsVolumeMetadataLister {
	return v1alpha1.NewCnsVolumeMetadataLister(f.Informer().GetIndexer())
}
