{
 "title": "CNS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vcenter",
    "label": "VC",
    "query": {
     "query": "label_values(jvm_threads_current, vcenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CSI-CNS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Success Rate (CNS operation success rate in last 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vsphere_cns_volume_ops_histogram_count{vcenter=\"$vcenter\", status=\"pass\"}[10m]))/sum(rate(vsphere_cns_volume_ops_histogram_count{vcenter=\"$vcenter\"}[10m]))*100"
    }
   ]
  },
  {
   "title": "Success Rates (CNS operation success rate by type over last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (optype) (rate(vsphere_cns_volume_ops_histogram_count{vcenter=\"$vcenter\", status=\"pass\"}[10m]))/sum by (optype) (rate(vsphere_cns_volume_ops_histogram_count{vcenter=\"$vcenter\"}[10m]))*100",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "99 Percentile Latency (99 Percentile CNS operations latency by type in last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (optype, le) (rate(vsphere_cns_volume_ops_histogram_bucket{vcenter=\"$vcenter\", status=\"pass\"}[10m])))",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "Avg Operation Latency (Average latency for CNS operations in last 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (optype) (rate(vsphere_cns_volume_ops_histogram_sum{vcenter=\"$vcenter\", status=\"pass\"}[10m]))/ sum by (optype) (rate(vsphere_cns_volume_ops_histogram_count {vcenter=\"$vcenter\", status=\"pass\"}[10m]))",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "90 Percentile latency(90 Percentile CNS operations latency by type in last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (optype, le) (rate(vsphere_cns_volume_ops_histogram_bucket{vcenter=\"$vcenter\", status=\"pass\"}[10m])))",
     "legendFormat": "{{optype}}"
    }
   ]
  }
 ]
}