{
 "title": "CSI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vcenter",
    "label": "VC",
    "query": {
     "query": "label_values(jvm_threads_current, vcenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CSI Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Volume Operation Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vsphere_csi_volume_ops_histogram_count{vcenter=\"$vcenter\",status=\"pass\"})/sum(vsphere_csi_volume_ops_histogram_count{vcenter=\"$vcenter\"})*100"
    }
   ]
  },
  {
   "title": "Success Rates (operation success rate over last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (optype) (rate(vsphere_csi_volume_ops_histogram_count{status=\"pass\"}[10m]))/sum by (optype) (rate(vsphere_csi_volume_ops_histogram_count[10m]))*100",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "Volume Ops Count (Total operation count)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (optype) (vsphere_csi_volume_ops_histogram_count{vcenter=\"$vcenter\"})",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "Avg Operation Latency (Average operation latency over last 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (optype) (rate(vsphere_csi_volume_ops_histogram_sum{status=\"pass\"}[10m]))/ sum by (optype) (rate(vsphere_csi_volume_ops_histogram_count {status=\"pass\"}[10m]))",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "90 Percentile Latency (90 Percentile operation latency in last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (optype, le) (rate(vsphere_csi_volume_ops_histogram_bucket{status=\"pass\"}[10m])))",
     "legendFormat": "{{optype}}"
    }
   ]
  },
  {
   "title": "99 Percentile Latency (99 Percentile operation latency in last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (optype, le) (rate(vsphere_csi_volume_ops_histogram_bucket{status=\"pass\"}[10m])))",
     "legendFormat": "{{optype}}"
    }
   ]
  }
 ]
}