#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail

lintout=$(mktemp)
lintout_filtered=$(mktemp)

function cleanup() {
	rm -f "$lintout" "$lintout_filtered"
}

trap cleanup EXIT

# Change directories to the parent directory of the one in which this
# script is located.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

go get golang.org/x/lint/golint

CMD=$(go list -f \{\{\.Target\}\} golang.org/x/lint/golint)

"${CMD}" ./pkg/... ./cmd/... ./tests/... > $lintout

# Remove autogenerated files from linter output
cat $lintout | sed '/generate/d; /pb/d; /proto/d; /CnsNodeVmAttachment/d' > $lintout_filtered

# Print lint errors
cat $lintout_filtered

# Exit with error code if lint checks failed
errors=`cat $lintout_filtered | wc -l`

if [ $errors -eq 0 ]; then
	exit 0
else
	exit 1
fi

