kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-vanilla-block-sc
provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - k8s-region-eu-all
          - k8s-zone-us-west
      - key: failure-domain.beta.kubernetes.io/region
        values:
          - k8s-region-eu
          - k8s-region-us
