apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-windows-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: example-windows-sc
  volumeMode: Filesystem
