//go:build !ignore_autogenerated

/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this into another CsiVolumeInfo instance.
func (in *CsiVolumeInfo) DeepCopyInto(out *CsiVolumeInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of CsiVolumeInfo.
func (in *CsiVolumeInfo) DeepCopy() *CsiVolumeInfo {
	if in == nil {
		return nil
	}
	out := new(CsiVolumeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CsiVolumeInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this into another CsiVolumeInfoList instance.
func (in *CsiVolumeInfoList) DeepCopyInto(out *CsiVolumeInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CsiVolumeInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CsiVolumeInfoList.
func (in *CsiVolumeInfoList) DeepCopy() *CsiVolumeInfoList {
	if in == nil {
		return nil
	}
	out := new(CsiVolumeInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CsiVolumeInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this into another CsiVolumeInfoSpec.
func (in *CsiVolumeInfoSpec) DeepCopyInto(out *CsiVolumeInfoSpec) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]VirtualMachineRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of CsiVolumeInfoSpec.
func (in *CsiVolumeInfoSpec) DeepCopy() *CsiVolumeInfoSpec {
	if in == nil {
		return nil
	}
	out := new(CsiVolumeInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this into another CsiVolumeInfoStatus.
func (in *CsiVolumeInfoStatus) DeepCopyInto(out *CsiVolumeInfoStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CsiVolumeInfoStatus.
func (in *CsiVolumeInfoStatus) DeepCopy() *CsiVolumeInfoStatus {
	if in == nil {
		return nil
	}
	out := new(CsiVolumeInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this into another VirtualMachineRef.
func (in *VirtualMachineRef) DeepCopyInto(out *VirtualMachineRef) {
	*out = *in
}

// DeepCopy returns a deep copy of VirtualMachineRef.
func (in *VirtualMachineRef) DeepCopy() *VirtualMachineRef {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineRef)
	in.DeepCopyInto(out)
	return out
}
