//go:build !ignore_autogenerated

// Copyright (c)  VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedReservedValues) DeepCopyInto(out *ExpectedReservedValues) {
	*out = *in
	if in.Reserved != nil {
		in, out := &in.Reserved, &out.Reserved
		*out = make(map[string]*resource.Quantity, len(*in))
		for key, val := range *in {
			{
				x := val.DeepCopy()
				(*out)[key] = &x
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedReservedValues.
func (in *ExpectedReservedValues) DeepCopy() *ExpectedReservedValues {
	if in == nil {
		return nil
	}
	out := new(ExpectedReservedValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageQuotaPeriodicSync) DeepCopyInto(out *StorageQuotaPeriodicSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageQuotaPeriodicSync.
func (in *StorageQuotaPeriodicSync) DeepCopy() *StorageQuotaPeriodicSync {
	if in == nil {
		return nil
	}
	out := new(StorageQuotaPeriodicSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageQuotaPeriodicSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageQuotaPeriodicSyncList) DeepCopyInto(out *StorageQuotaPeriodicSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageQuotaPeriodicSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageQuotaPeriodicSyncList.
func (in *StorageQuotaPeriodicSyncList) DeepCopy() *StorageQuotaPeriodicSyncList {
	if in == nil {
		return nil
	}
	out := new(StorageQuotaPeriodicSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageQuotaPeriodicSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageQuotaPeriodicSyncSpec) DeepCopyInto(out *StorageQuotaPeriodicSyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageQuotaPeriodicSyncSpec.
func (in *StorageQuotaPeriodicSyncSpec) DeepCopy() *StorageQuotaPeriodicSyncSpec {
	if in == nil {
		return nil
	}
	out := new(StorageQuotaPeriodicSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageQuotaPeriodicSyncStatus) DeepCopyInto(out *StorageQuotaPeriodicSyncStatus) {
	*out = *in
	in.LastSyncTimestamp.DeepCopyInto(&out.LastSyncTimestamp)
	if in.ExpectedReservedValues != nil {
		in, out := &in.ExpectedReservedValues, &out.ExpectedReservedValues
		*out = make([]ExpectedReservedValues, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageQuotaPeriodicSyncStatus.
func (in *StorageQuotaPeriodicSyncStatus) DeepCopy() *StorageQuotaPeriodicSyncStatus {
	if in == nil {
		return nil
	}
	out := new(StorageQuotaPeriodicSyncStatus)
	in.DeepCopyInto(out)
	return out
}
