//go:build !ignore_autogenerated

// Copyright (c) 2025 Broadcom. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileVolume) DeepCopyInto(out *FileVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileVolume.
func (in *FileVolume) DeepCopy() *FileVolume {
	if in == nil {
		return nil
	}
	out := new(FileVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileVolumeList) DeepCopyInto(out *FileVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FileVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileVolumeList.
func (in *FileVolumeList) DeepCopy() *FileVolumeList {
	if in == nil {
		return nil
	}
	out := new(FileVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileVolumeSpec) DeepCopyInto(out *FileVolumeSpec) {
	*out = *in
	in.Size.DeepCopyInto(&out.Size)
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]FileVolumeProtocol, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileVolumeSpec.
func (in *FileVolumeSpec) DeepCopy() *FileVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(FileVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileVolumeStatus) DeepCopyInto(out *FileVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastAppliedSize.DeepCopyInto(&out.LastAppliedSize)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileVolumeStatus.
func (in *FileVolumeStatus) DeepCopy() *FileVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(FileVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
