/*
 * CNS Manager
 *
 * **CNS Manager** helps detect and auto
 remediate all the storage control plane known issues
 in the CNS solution.
 CNS Manager exposes APIs that can be invoked by authorized users to detect,
 remediate and troubleshoot problems.
 CNS manager also continuously and periodically monitors the system
 for all the known issues and exposes relevant metrics in the Prometheus format.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
*/
package cnsutils

type Fault struct {
	Message   string `json:"message"`
	FaultType string `json:"faultType"`
}
