/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/cnsvolumemetadata/v1alpha1"
	scheme "sigs.k8s.io/vsphere-csi-driver/pkg/syncer/cnsoperator/client/clientset/versioned/scheme"
)

// CnsVolumeMetadatasGetter has a method to return a CnsVolumeMetadataInterface.
// A group's client should implement this interface.
type CnsVolumeMetadatasGetter interface {
	CnsVolumeMetadatas(namespace string) CnsVolumeMetadataInterface
}

// CnsVolumeMetadataInterface has methods to work with CnsVolumeMetadata resources.
type CnsVolumeMetadataInterface interface {
	Create(*v1alpha1.CnsVolumeMetadata) (*v1alpha1.CnsVolumeMetadata, error)
	Update(*v1alpha1.CnsVolumeMetadata) (*v1alpha1.CnsVolumeMetadata, error)
	UpdateStatus(*v1alpha1.CnsVolumeMetadata) (*v1alpha1.CnsVolumeMetadata, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CnsVolumeMetadata, error)
	List(opts v1.ListOptions) (*v1alpha1.CnsVolumeMetadataList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CnsVolumeMetadata, err error)
	CnsVolumeMetadataExpansion
}

// cnsVolumeMetadatas implements CnsVolumeMetadataInterface
type cnsVolumeMetadatas struct {
	client rest.Interface
	ns     string
}

// newCnsVolumeMetadatas returns a CnsVolumeMetadatas
func newCnsVolumeMetadatas(c *CnsV1alpha1Client, namespace string) *cnsVolumeMetadatas {
	return &cnsVolumeMetadatas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cnsVolumeMetadata, and returns the corresponding cnsVolumeMetadata object, and an error if there is any.
func (c *cnsVolumeMetadatas) Get(name string, options v1.GetOptions) (result *v1alpha1.CnsVolumeMetadata, err error) {
	result = &v1alpha1.CnsVolumeMetadata{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CnsVolumeMetadatas that match those selectors.
func (c *cnsVolumeMetadatas) List(opts v1.ListOptions) (result *v1alpha1.CnsVolumeMetadataList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CnsVolumeMetadataList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cnsVolumeMetadatas.
func (c *cnsVolumeMetadatas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cnsVolumeMetadata and creates it.  Returns the server's representation of the cnsVolumeMetadata, and an error, if there is any.
func (c *cnsVolumeMetadatas) Create(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (result *v1alpha1.CnsVolumeMetadata, err error) {
	result = &v1alpha1.CnsVolumeMetadata{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		Body(cnsVolumeMetadata).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cnsVolumeMetadata and updates it. Returns the server's representation of the cnsVolumeMetadata, and an error, if there is any.
func (c *cnsVolumeMetadatas) Update(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (result *v1alpha1.CnsVolumeMetadata, err error) {
	result = &v1alpha1.CnsVolumeMetadata{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		Name(cnsVolumeMetadata.Name).
		Body(cnsVolumeMetadata).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cnsVolumeMetadatas) UpdateStatus(cnsVolumeMetadata *v1alpha1.CnsVolumeMetadata) (result *v1alpha1.CnsVolumeMetadata, err error) {
	result = &v1alpha1.CnsVolumeMetadata{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		Name(cnsVolumeMetadata.Name).
		SubResource("status").
		Body(cnsVolumeMetadata).
		Do().
		Into(result)
	return
}

// Delete takes name of the cnsVolumeMetadata and deletes it. Returns an error if one occurs.
func (c *cnsVolumeMetadatas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cnsVolumeMetadatas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cnsVolumeMetadata.
func (c *cnsVolumeMetadatas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CnsVolumeMetadata, err error) {
	result = &v1alpha1.CnsVolumeMetadata{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cnsvolumemetadatas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
