// Code generated by protoc-gen-go.
// source: k8scloudoperator.proto
// DO NOT EDIT!

/*
Package k8scloudoperator is a generated protocol buffer package.

It is generated from these files:
	k8scloudoperator.proto

It has these top-level messages:
	PodListenerRequest
	PodListenerResponse
	HostAnnotationRequest
	HostAnnotationResponse
*/
package k8scloudoperator

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PodListenerRequest struct {
	// The volumeID that needs to be attached to the node.
	VolumeID string `protobuf:"bytes,1,opt,name=volumeID" json:"volumeID,omitempty"`
	// Name of the node where the Pod is running.
	NodeName string `protobuf:"bytes,2,opt,name=nodeName" json:"nodeName,omitempty"`
}

func (m *PodListenerRequest) Reset()                    { *m = PodListenerRequest{} }
func (m *PodListenerRequest) String() string            { return proto.CompactTextString(m) }
func (*PodListenerRequest) ProtoMessage()               {}
func (*PodListenerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PodListenerResponse struct {
	// VM UUID annotation of the pod.
	VmuuidAnnotation string `protobuf:"bytes,1,opt,name=vmuuidAnnotation" json:"vmuuidAnnotation,omitempty"`
}

func (m *PodListenerResponse) Reset()                    { *m = PodListenerResponse{} }
func (m *PodListenerResponse) String() string            { return proto.CompactTextString(m) }
func (*PodListenerResponse) ProtoMessage()               {}
func (*PodListenerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HostAnnotationRequest struct {
	// Name of the host
	HostName string `protobuf:"bytes,1,opt,name=hostName" json:"hostName,omitempty"`
	// Name of the annotation key of interest
	AnnotationKey string `protobuf:"bytes,2,opt,name=annotationKey" json:"annotationKey,omitempty"`
}

func (m *HostAnnotationRequest) Reset()                    { *m = HostAnnotationRequest{} }
func (m *HostAnnotationRequest) String() string            { return proto.CompactTextString(m) }
func (*HostAnnotationRequest) ProtoMessage()               {}
func (*HostAnnotationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HostAnnotationResponse struct {
	// Value of the annotation key on the node `hostName`
	AnnotationValue string `protobuf:"bytes,2,opt,name=annotationValue" json:"annotationValue,omitempty"`
}

func (m *HostAnnotationResponse) Reset()                    { *m = HostAnnotationResponse{} }
func (m *HostAnnotationResponse) String() string            { return proto.CompactTextString(m) }
func (*HostAnnotationResponse) ProtoMessage()               {}
func (*HostAnnotationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*PodListenerRequest)(nil), "k8scloudoperator.PodListenerRequest")
	proto.RegisterType((*PodListenerResponse)(nil), "k8scloudoperator.PodListenerResponse")
	proto.RegisterType((*HostAnnotationRequest)(nil), "k8scloudoperator.HostAnnotationRequest")
	proto.RegisterType((*HostAnnotationResponse)(nil), "k8scloudoperator.HostAnnotationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for K8SCloudOperator service

type K8SCloudOperatorClient interface {
	//
	// GetPodVMUUIDAnnotation gets the PV by querying the API server refering to the volumeID in the request.
	// Retrieves the PVC name and Namespace from the PV spec.
	//
	// It then gets the vmuuid annotation from the pod satisfying the below conditions
	// 1. Pod Scheduled on node with name "nodeName"
	// 2. Pod is in pending state in the same namespace as pvc specified using "pvcNamespace"
	// 3. Pod has a volume with name "pvcName" associated with it
	//
	// The annotation might not be available immediately when the Pod is created.
	// So polling the Pod periodically every pollInterval seconds to check if annotation is available.
	// If annotation is not available after a timeout period, the function errors out.
	GetPodVMUUIDAnnotation(ctx context.Context, in *PodListenerRequest, opts ...grpc.CallOption) (*PodListenerResponse, error)
	//
	// GetHostAnnotation gets the annotation value by querying the API server referring to the annotation key
	// and the host specified in the HostAnnotationRequest
	GetHostAnnotation(ctx context.Context, in *HostAnnotationRequest, opts ...grpc.CallOption) (*HostAnnotationResponse, error)
}

type k8SCloudOperatorClient struct {
	cc *grpc.ClientConn
}

func NewK8SCloudOperatorClient(cc *grpc.ClientConn) K8SCloudOperatorClient {
	return &k8SCloudOperatorClient{cc}
}

func (c *k8SCloudOperatorClient) GetPodVMUUIDAnnotation(ctx context.Context, in *PodListenerRequest, opts ...grpc.CallOption) (*PodListenerResponse, error) {
	out := new(PodListenerResponse)
	err := grpc.Invoke(ctx, "/k8scloudoperator.K8sCloudOperator/GetPodVMUUIDAnnotation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SCloudOperatorClient) GetHostAnnotation(ctx context.Context, in *HostAnnotationRequest, opts ...grpc.CallOption) (*HostAnnotationResponse, error) {
	out := new(HostAnnotationResponse)
	err := grpc.Invoke(ctx, "/k8scloudoperator.K8sCloudOperator/GetHostAnnotation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for K8SCloudOperator service

type K8SCloudOperatorServer interface {
	//
	// GetPodVMUUIDAnnotation gets the PV by querying the API server refering to the volumeID in the request.
	// Retrieves the PVC name and Namespace from the PV spec.
	//
	// It then gets the vmuuid annotation from the pod satisfying the below conditions
	// 1. Pod Scheduled on node with name "nodeName"
	// 2. Pod is in pending state in the same namespace as pvc specified using "pvcNamespace"
	// 3. Pod has a volume with name "pvcName" associated with it
	//
	// The annotation might not be available immediately when the Pod is created.
	// So polling the Pod periodically every pollInterval seconds to check if annotation is available.
	// If annotation is not available after a timeout period, the function errors out.
	GetPodVMUUIDAnnotation(context.Context, *PodListenerRequest) (*PodListenerResponse, error)
	//
	// GetHostAnnotation gets the annotation value by querying the API server referring to the annotation key
	// and the host specified in the HostAnnotationRequest
	GetHostAnnotation(context.Context, *HostAnnotationRequest) (*HostAnnotationResponse, error)
}

func RegisterK8SCloudOperatorServer(s *grpc.Server, srv K8SCloudOperatorServer) {
	s.RegisterService(&_K8SCloudOperator_serviceDesc, srv)
}

func _K8SCloudOperator_GetPodVMUUIDAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SCloudOperatorServer).GetPodVMUUIDAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8scloudoperator.K8sCloudOperator/GetPodVMUUIDAnnotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SCloudOperatorServer).GetPodVMUUIDAnnotation(ctx, req.(*PodListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SCloudOperator_GetHostAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostAnnotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SCloudOperatorServer).GetHostAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8scloudoperator.K8sCloudOperator/GetHostAnnotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SCloudOperatorServer).GetHostAnnotation(ctx, req.(*HostAnnotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _K8SCloudOperator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "k8scloudoperator.K8sCloudOperator",
	HandlerType: (*K8SCloudOperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodVMUUIDAnnotation",
			Handler:    _K8SCloudOperator_GetPodVMUUIDAnnotation_Handler,
		},
		{
			MethodName: "GetHostAnnotation",
			Handler:    _K8SCloudOperator_GetHostAnnotation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k8scloudoperator.proto",
}

func init() { proto.RegisterFile("k8scloudoperator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0x1e, 0x44, 0x07, 0xc4, 0xb8, 0x62, 0x28, 0x39, 0x49, 0xa8, 0x18, 0x3c, 0xf4, 0xa0,
	0x97, 0x5e, 0xab, 0x85, 0x5a, 0x5a, 0xb5, 0x14, 0x5a, 0xf0, 0x18, 0xdd, 0xc1, 0x06, 0x93, 0x9d,
	0x98, 0x9d, 0x2d, 0xf8, 0xc1, 0xfe, 0x87, 0xb4, 0xdd, 0x34, 0x26, 0x29, 0xf4, 0x38, 0x6f, 0x66,
	0xde, 0x7b, 0xf3, 0x76, 0xc1, 0xfb, 0xea, 0xea, 0x8f, 0x84, 0x8c, 0xa4, 0x0c, 0xf3, 0x88, 0x29,
	0xef, 0x64, 0x39, 0x31, 0x09, 0xb7, 0x8e, 0x07, 0x63, 0x10, 0x13, 0x92, 0xe3, 0x58, 0x33, 0x2a,
	0xcc, 0xa7, 0xf8, 0x6d, 0x50, 0xb3, 0xf0, 0xe1, 0x78, 0x49, 0x89, 0x49, 0x71, 0xd8, 0x6f, 0x39,
	0x57, 0x4e, 0x78, 0x32, 0xdd, 0xd6, 0xab, 0x9e, 0x22, 0x89, 0x2f, 0x51, 0x8a, 0xad, 0xc3, 0x4d,
	0xaf, 0xa8, 0x83, 0x1e, 0x5c, 0x54, 0xd8, 0x74, 0x46, 0x4a, 0xa3, 0xb8, 0x05, 0x77, 0x99, 0x1a,
	0x13, 0xcb, 0x9e, 0x52, 0xc4, 0x11, 0xc7, 0xa4, 0x2c, 0x6d, 0x03, 0x0f, 0xde, 0xe0, 0xf2, 0x89,
	0x34, 0x97, 0xc8, 0x3f, 0x4f, 0x0b, 0xd2, 0xbc, 0xd6, 0xb5, 0x9e, 0x8a, 0x5a, 0xb4, 0xe1, 0x34,
	0xda, 0x2e, 0x8c, 0xf0, 0xc7, 0x1a, 0xab, 0x82, 0xc1, 0x03, 0x78, 0x75, 0x6a, 0x6b, 0x30, 0x84,
	0xb3, 0x72, 0x74, 0x1e, 0x25, 0xa6, 0x38, 0xad, 0x0e, 0xdf, 0xfd, 0x3a, 0xe0, 0x8e, 0xba, 0xfa,
	0x71, 0x15, 0xe2, 0xab, 0x0d, 0x51, 0x7c, 0x82, 0x37, 0x40, 0x9e, 0x90, 0x9c, 0x3f, 0xcf, 0x66,
	0xc3, 0x7e, 0x29, 0x20, 0xda, 0x9d, 0xc6, 0x4b, 0x34, 0xe3, 0xf6, 0xaf, 0xf7, 0x4c, 0x6d, 0x5c,
	0x06, 0x07, 0x62, 0x01, 0xe7, 0x03, 0xe4, 0xea, 0x11, 0xe2, 0xa6, 0xb9, 0xbd, 0x33, 0x41, 0x3f,
	0xdc, 0x3f, 0x58, 0x28, 0xbd, 0x1f, 0xad, 0x3f, 0xcc, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xee, 0xac, 0xa3, 0x30, 0x4a, 0x02, 0x00, 0x00,
}
