kind: Deployment
apiVersion: apps/v1
metadata:
  name: vsphere-csi-controller
  namespace: vmware-system-csi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: vsphere-csi-controller
  template:
    metadata:
      labels:
        app: vsphere-csi-controller
        role: vsphere-csi
    spec:
      serviceAccountName: vsphere-csi-controller
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - operator: "Exists"
          key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: csi-attacher
          image: vmware/csi-attacher/csi-attacher:<csi_attacher_ver>
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-type=leases"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: vsphere-csi-controller
          image: vmware/vsphere-csi:<vsphere_csi_ver>
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /var/lib/csi/sockets/pluginproxy/csi.vsphere.vmware.com"]
          args:
            - "--v=4"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: CLUSTER_FLAVOR
              value: "GUEST_CLUSTER"
            - name: X_CSI_MODE
              value: "controller"
            - name: X_CSI_GC_CONFIG
              value: /etc/cloud/pvcsi-config/cns-csi.conf
            - name: PROVISION_TIMEOUT_MINUTES
              value: "4"
            - name: ATTACHER_TIMEOUT_MINUTES
              value: "4"
            - name: LOGGER_LEVEL
              value: "DEVELOPMENT" # Options: DEVELOPMENT, PRODUCTION
          volumeMounts:
            - mountPath: /etc/cloud/pvcsi-provider
              name: pvcsi-provider-volume
              readOnly: true
            - mountPath: /etc/cloud/pvcsi-config
              name: pvcsi-config-volume
              readOnly: true
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: vsphere-syncer
          image: vmware/syncer:<vsphere_csi_ver>
          args:
            - "--v=4"
            - "--leader-election"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: X_CSI_FULL_SYNC_INTERVAL_MINUTES
              value: "30"
            - name: X_CSI_GC_CONFIG
              value: /etc/cloud/pvcsi-config/cns-csi.conf
            - name: CLUSTER_FLAVOR
              value: "GUEST_CLUSTER"
            - name: LOGGER_LEVEL
              value: "DEVELOPMENT" # Options: DEVELOPMENT, PRODUCTION
          volumeMounts:
          - mountPath: /etc/cloud/pvcsi-provider
            name: pvcsi-provider-volume
            readOnly: true
          - mountPath: /etc/cloud/pvcsi-config
            name: pvcsi-config-volume
            readOnly: true
        - name: liveness-probe
          image: vmware/csi-livenessprobe/csi-livenessprobe:<csi_livenessprobe_ver>
          args:
            - "--csi-address=$(ADDRESS)"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: csi-provisioner
          image: vmware/csi-provisioner/csi-provisioner:<csi_provisioner_ver>
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
            - "--leader-election-type=leases"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
         - name: pvcsi-provider-volume
           secret:
             secretName: pvcsi-provider-creds
         - name: pvcsi-config-volume
           configMap:
             name: pvcsi-config
         - name: socket-dir
           hostPath:
             path: /var/lib/csi/sockets/pluginproxy/csi.vsphere.vmware.com
             type: DirectoryOrCreate
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.vsphere.vmware.com
spec:
  attachRequired: true
  podInfoOnMount: false